In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('Social_Network_Ads.csv')

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dep=dataset['Purchased']

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [10]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'splitter':['best','random']} 



grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END criterion=gini, max_features=auto, splitter=best;, score=0.822 total time=   0.0s
[CV 2/5] END criterion=gini, max_features=auto, splitter=best;, score=0.796 total time=   0.0s
[CV 3/5] END criterion=gini, max_features=auto, splitter=best;, score=0.852 total time=   0.0s
[CV 4/5] END criterion=gini, max_features=auto, splitter=best;, score=0.832 total time=   0.0s
[CV 5/5] END criterion=gini, max_features=auto, splitter=best;, score=0.924 total time=   0.0s
[CV 1/5] END criterion=gini, max_features=auto, splitter=random;, score=0.783 total time=   0.0s
[CV 2/5] END criterion=gini, max_features=auto, splitter=random;, score=0.849 total time=   0.0s
[CV 3/5] END criterion=gini, max_features=auto, splitter=random;, score=0.832 total time=   0.0s
[CV 4/5] END criterion=gini, max_features=auto, splitter=random;, score=0.794 total time=   0.0s
[CV 5/5] END criterion=gini, max_features=auto, splitter=random;, score=0.831 total time=   0.0s
[CV 1/5] END criterion=gini, max_features=sqrt, splitter=best;, score=0.826 total time=   0.0s
[CV 2/5] END criterion=gini, max_features=sqrt, splitter=best;, score=0.833 total time=   0.0s
[CV 3/5] END criterion=gini, max_features=sqrt, splitter=best;, score=0.852 total time=   0.0s
[CV 4/5] END criterion=gini, max_features=sqrt, splitter=best;, score=0.852 total time=   0.0s
[CV 5/5] END criterion=gini, max_features=sqrt, splitter=best;, score=0.925 total time=   0.0s
[CV 1/5] END criterion=gini, max_features=sqrt, splitter=random;, score=0.844 total time=   0.0s
[CV 2/5] END criterion=gini, max_features=sqrt, splitter=random;, score=0.870 total time=   0.0s
[CV 3/5] END criterion=gini, max_features=sqrt, splitter=random;, score=0.738 total time=   0.0s
[CV 4/5] END criterion=gini, max_features=sqrt, splitter=random;, score=0.831 total time=   0.0s
[CV 5/5] END criterion=gini, max_features=sqrt, splitter=random;, score=0.831 total time=   0.0s
[CV 1/5] END criterion=gini, max_features=log2, splitter=best;, score=0.805 total time=   0.0s
[CV 2/5] END criterion=gini, max_features=log2, splitter=best;, score=0.852 total time=   0.0s
[CV 3/5] END criterion=gini, max_features=log2, splitter=best;, score=0.813 total time=   0.0s
[CV 4/5] END criterion=gini, max_features=log2, splitter=best;, score=0.832 total time=   0.0s
[CV 5/5] END criterion=gini, max_features=log2, splitter=best;, score=0.844 total time=   0.0s
[CV 1/5] END criterion=gini, max_features=log2, splitter=random;, score=0.783 total time=   0.0s
[CV 2/5] END criterion=gini, max_features=log2, splitter=random;, score=0.867 total time=   0.0s
[CV 3/5] END criterion=gini, max_features=log2, splitter=random;, score=0.776 total time=   0.0s
[CV 4/5] END criterion=gini, max_features=log2, splitter=random;, score=0.809 total time=   0.0s
[CV 5/5] END criterion=gini, max_features=log2, splitter=random;, score=0.823 total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=auto, splitter=best;, score=0.826 total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=auto, splitter=best;, score=0.831 total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=auto, splitter=best;, score=0.814 total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=auto, splitter=best;, score=0.906 total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=auto, splitter=best;, score=0.887 total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=auto, splitter=random;, score=0.832 total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=auto, splitter=random;, score=0.831 total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=auto, splitter=random;, score=0.741 total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=auto, splitter=random;, score=0.906 total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=auto, splitter=random;, score=0.943 total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=sqrt, splitter=best;, score=0.826 total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=sqrt, splitter=best;, score=0.849 total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=sqrt, splitter=best;, score=0.852 total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=sqrt, splitter=best;, score=0.870 total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=sqrt, splitter=best;, score=0.924 total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=sqrt, splitter=random;, score=0.783 total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=sqrt, splitter=random;, score=0.794 total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=sqrt, splitter=random;, score=0.736 total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=sqrt, splitter=random;, score=0.887 total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=sqrt, splitter=random;, score=0.862 total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=log2, splitter=best;, score=0.805 total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=log2, splitter=best;, score=0.833 total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=log2, splitter=best;, score=0.833 total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=log2, splitter=best;, score=0.831 total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=log2, splitter=best;, score=0.847 total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=log2, splitter=random;, score=0.812 total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=log2, splitter=random;, score=0.794 total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=log2, splitter=random;, score=0.777 total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=log2, splitter=random;, score=0.925 total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=log2, splitter=random;, score=0.943 total time=   0.0s

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [11]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [12]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'sqrt', 'splitter': 'best'}: 0.9027686670643886

In [13]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[79  6]
 [ 7 42]]

In [14]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.92      0.93      0.92        85
           1       0.88      0.86      0.87        49

    accuracy                           0.90       134
   macro avg       0.90      0.89      0.89       134
weighted avg       0.90      0.90      0.90       134

In [15]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.8932773109243698

In [16]:
table=pd.DataFrame.from_dict(re)

In [17]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004325,0.007200,0.001805,0.001643,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",0.822092,0.795789,0.851527,0.832483,0.923510,0.845080,0.043150,6
1,0.001119,0.000741,0.001319,0.000421,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",0.782557,0.849057,0.832483,0.793565,0.831098,0.817752,0.025294,10
2,0.001272,0.000380,0.000998,0.000005,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.826263,0.832918,0.851527,0.851527,0.924528,0.857353,0.035054,2
3,0.000265,0.000531,0.000000,0.000000,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.843811,0.870047,0.738451,0.831098,0.831098,0.822901,0.044556,9
4,0.003175,0.006350,0.003131,0.006262,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.804764,0.852030,0.813179,0.832483,0.844370,0.829365,0.017977,8
5,0.000000,0.000000,0.000000,0.000000,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.782557,0.866968,0.775815,0.808775,0.823140,0.811451,0.032652,12
6,0.000000,0.000000,0.000000,0.000000,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",0.826263,0.831253,0.814409,0.906166,0.886792,0.852977,0.036457,3
7,0.000000,0.000000,0.000000,0.000000,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",0.832255,0.831253,0.741078,0.906166,0.943041,0.850759,0.069769,4
8,0.001077,0.000640,0.001120,0.000714,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.826263,0.849057,0.851527,0.870362,0.923510,0.864144,0.032817,1
9,0.001116,0.000101,0.001182,0.000750,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.782557,0.793754,0.735849,0.886792,0.862442,0.812279,0.055021,11
10,0.001790,0.001215,0.002400,0.000937,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.804764,0.832918,0.833323,0.831098,0.847020,0.829825,0.013763,7
11,0.001273,0.000308,0.001100,0.000204,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.812243,0.793754,0.777291,0.925272,0.943041,0.850320,0.069567,5

In [18]:
age_input = float(input("Enter Age: "))
salary_input = float(input("Enter Estimated Salary: "))
gender_input = int(input("Gender Male? (1 = Male, 0 = Female): "))

Enter Age: 34
Enter Estimated Salary: 30000
Gender Male? (1 = Male, 0 = Female): 0

In [19]:
# important: apply same scaling
user_data = sc.transform([[age_input, salary_input, gender_input]])

C:\Anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"

In [20]:
Future_Prediction = grid.predict(user_data)

print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[0]